// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Model;
using System;
using System.Collections.Generic;

namespace Model;

public partial class Coupon
{
    public int Id { get; set; }

    public string Code { get; set; }

    public decimal DiscountAmount { get; set; }

    public DateTime ExpirationDate { get; set; }

    public int Quantity { get; set; }

    public int UsedCount { get; set; }

    public int? UserId { get; set; }

    public virtual User User { get; set; }
}