// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model;

public partial class Order
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Status { get; set; }

    public int? PaymentMethodId { get; set; }

    public int? BillingAddressId { get; set; }

    public virtual Billingaddress BillingAddress { get; set; }

    public virtual ICollection<Orderdetail> Orderdetails { get; set; } = new List<Orderdetail>();

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual User User { get; set; }
}