// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model;

public partial class Orderdetail
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public string ProductName { get; set; }

    public string ProductDescription { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal Subtotal { get; set; }

    public virtual Order Order { get; set; }
}