// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model;

public partial class PaymentMethod
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string PaymentType { get; set; }

    public string PaymentDetails { get; set; }

    public DateTime? CreationDate { get; set; }

    public bool? IsPrimary { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual User User { get; set; }
}