// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 
    
    Model;

public partial class Shoppingcartitem
{
    public int Id { get; set; }

    public int ShoppingCartId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public DateTime AddedAt { get; set; }
    public bool? Active { get; set; }
    public virtual Product Product { get; set; }

    public virtual Shoppingcart ShoppingCart { get; set; }
}