// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model;

public partial class Token
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string TokenValue { get; set; }

    public DateTime Expiration { get; set; }

    public virtual User User { get; set; }
}