// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataModel;

public partial class AdministratorDto
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public virtual string UserFullName { get; set; }
}