// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataModel;

public class BillingaddressDto
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Country { get; set; }

    public string State { get; set; }

    public string City { get; set; }

    public string Street { get; set; }

    public string StreetNumber { get; set; }

    public string Door { get; set; }

    public string Block { get; set; }

    public string Floor { get; set; }

    public string PostalCode { get; set; }

    public bool? IsPrimary { get; set; }

    public DateTime? CreationDate { get; set; }

    public string UserFullName { get; set; }
}