// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataModel;

public  class DiscountDto
{
    public int Id { get; set; }

    public string Code { get; set; }

    public decimal? Amount { get; set; }

    public string DiscountType { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? Active { get; set; }

}