// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataModel;

public class OrderDto
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public decimal TotalAmount { get; set; }

    public string BillingAddress { get; set; }

    public DateTime OrderDate { get; set; }

    public string OrderStatus { get; set; }

    public virtual string UserFullName { get; set; }
}