// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataModel;

public class OrderDto
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public DateTime? OrderDate { get; set; }

    public string Status { get; set; }

    public int? PaymentMethodId { get; set; }

    public int? BillingAddressId { get; set; }

    public string UserFullName { get; set; }
}