// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataModel;

public class PaymentMethodDto
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string PaymentType { get; set; }

    public string PaymentDetails { get; set; }

    public DateTime? CreationDate { get; set; }

    public bool? IsPrimary { get; set; }

    public string UserFullName { get; set; }
}