// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataModel;

public class ProductDto
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public int? Stock { get; set; }

    public int? CategoryId { get; set; }

    public string Image { get; set; }

    public DateTime? CreationDate { get; set; }

    public bool? Active { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public int? DiscountId { get; set; }

    public string CategoryName { get; set; }

    public string DiscountCode { get; set; }

    public DiscountDto? Discount { get; set; }
}