// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataModel;

public class ShoppingcartDto
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? ProductId { get; set; }

    public bool Active { get; set; }

    public int? Quantity { get; set; }

    public DateTime? AddedDate { get; set; }

    public string ProductName { get; set; }

    public string UserFullName { get; set; }
}