// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Model;

public partial class ShoppingcartitemDto
{
    public int Id { get; set; }

    public int ShoppingCartId { get; set; }

    public int ProductId { get; set; }

    public string ProductName { get; set; }  // Derived from Product

    public int Quantity { get; set; }

    public decimal UnitPrice { get; set; }
    public  bool Active { get; set; }

    public DateTime AddedAt { get; set; }
}