// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace DataModel;

public class UserDto
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Avatar { get; set; }

    public bool EmailConfirmed { get; set; } = false;
    public string Password { get; set; }

    public DateTime? RegistrationDate { get; set; }
}